#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
הקלאס הראשי לשליפת נתוני ביטוח חובה
שולף נתונים עבור: רכב פרטי,מסחרי ומיוחד
יוצר תמונה עם טבלאות ונתונים ויוצר MDB
"""

import os
import re
import builtins
import sys
import threading
from datetime import datetime, timedelta

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import requests
from bs4 import BeautifulSoup

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import config

CHROME_UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
)
REQUEST_HEADERS = {
    "User-Agent": CHROME_UA,
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
    "Accept-Language": "he-IL,he;q=0.9,en-US;q=0.8,en;q=0.7",
    "Origin": getattr(config, "CMA_CAR_BASE_URL", "https://car.cma.gov.il"),
    "Referer": config.MINISTRY_OF_TRANSPORT_URL,
}
REQUEST_TIMEOUT = 30
PRICE_MIN = 100

PRIVATE_SCENARIOS = [
    (19, 900, 2), (19, 1200, 2), (19, 1800, 2), (19, 2200, 2),
    (22, 900, 4), (22, 1200, 4), (22, 1800, 4), (22, 2200, 4),
    (25, 900, 7), (25, 1200, 7), (25, 1800, 7), (25, 2200, 7),
    (31, 900, 13), (31, 1200, 13), (31, 1800, 13), (31, 2200, 13),
    (41, 900, 23), (41, 1200, 23), (41, 1800, 23), (41, 2200, 23),
    (51, 900, 33), (51, 1200, 33), (51, 1800, 33), (51, 2200, 33),
]
COMMERCIAL_SCENARIOS = [
    (19, 4, 1), (19, 4.5, 1), (23, 4, 5), (23, 4.5, 5),
    (25, 4, 7), (25, 4.5, 7), (43, 4, 17), (43, 4.5, 17), (52, 4, 26), (52, 4.5, 26),
]
SPECIAL_SCENARIOS = [
    ("Nigrar", "35"),
    ("Handasi", "4"),
    ("Agricalture", "11"),
]


def _import_mdb_module():
    """ייבוא simple_mdb_creator – עובד גם מ-EXE וגם מהקוד."""
    try:
        from BituahRechev import simple_mdb_creator as mdb
    except ImportError:
        import simple_mdb_creator as mdb
    return mdb


def print(*args, **kwargs):
    """הדפסה בטוחה ב-Windows (מונע UnicodeEncodeError מאימוג'י בטרמינל)."""
    try:
        builtins.print(*args, **kwargs)
    except UnicodeEncodeError:
        sep = kwargs.get("sep", " ")
        end = kwargs.get("end", "\n")
        file_obj = kwargs.get("file", sys.stdout)
        flush = kwargs.get("flush", False)
        text = sep.join(str(a) for a in args)
        encoding = getattr(file_obj, "encoding", None) or "utf-8"
        safe_text = text.encode(encoding, errors="ignore").decode(encoding, errors="ignore")
        builtins.print(safe_text, end=end, file=file_obj, flush=flush)


def _create_http_session(impersonate=False):
    """יוצר Session עם כותרות דפדפן. impersonate=True משתמש ב-curl_cffi נגד CloudFront."""
    if impersonate:
        from curl_cffi import requests as cffi_requests
        session = cffi_requests.Session(impersonate="chrome")
    else:
        session = requests.Session()
    session.headers.update(REQUEST_HEADERS)
    return session


def _is_waf_error(exc):
    text = str(exc)
    text_l = text.lower()
    return "חסם את הבקשה" in text or "awswaf" in text_l or " 202" in text_l or " 403" in text_l


def _response_blocked(response):
    if response is None:
        return True
    if response.status_code in (403, 503):
        return True
    text = (response.text or "")[:2000].lower()
    if "request blocked" in text or "generated by cloudfront" in text or "awswaf" in text:
        return True
    if response.status_code == 202 and "insurance_date" not in text and "myform" not in text:
        return True
    return False


class InsuranceScraper:
    def __init__(self):
        self.driver = None
        self.session = None
        self._session_kind = None
        self.insurance_date = None
        self._session_lock = threading.Lock()

    def cleanup(self):
        try:
            if self.session is not None:
                self.session.close()
        except Exception:
            pass
        self.session = None

    def _clone_session(self):
        """Session נפרד ל-thread, עם אותם cookies."""
        impersonate = self._session_kind == "curl_cffi"
        cloned = _create_http_session(impersonate=impersonate)
        try:
            cloned.cookies.update(self.session.cookies)
        except Exception:
            for cookie in self.session.cookies:
                cloned.cookies.set(cookie.name, cookie.value, domain=getattr(cookie, "domain", None))
        return cloned

    def _apply_cookies(self, session, cookies):
        for cookie in cookies or []:
            domain = (cookie.get("domain") or "car.cma.gov.il").lstrip(".")
            try:
                session.cookies.set(cookie["name"], cookie["value"], domain=domain)
            except Exception:
                session.cookies.set(cookie["name"], cookie["value"])

    def _bootstrap_waf_cookies(self):
        """
        CloudFront/AWS WAF דורש הרצת JS בדפדפן.
        פותחים Chrome פעם אחת, לוקחים cookies, וסוגרים.
        """
        options = webdriver.ChromeOptions()
        options.add_argument("--no-sandbox")
        options.add_argument("--disable-dev-shm-usage")
        options.add_argument("--disable-gpu")
        options.add_argument("--window-size=900,700")
        driver = webdriver.Chrome(options=options)
        try:
            driver.get(config.MINISTRY_OF_TRANSPORT_URL)
            WebDriverWait(driver, 40).until(
                EC.presence_of_element_located((By.ID, "insurance_date"))
            )
            date = driver.find_element(By.ID, "insurance_date").get_attribute("value") or ""
            cookies = driver.get_cookies()
            print(f"WAF cookies נקלטו ({len(cookies)}), תאריך ביטוח: {date}")
            return date.strip(), cookies
        finally:
            try:
                driver.quit()
            except Exception:
                pass

    def _ensure_session(self, force=False):
        with self._session_lock:
            if not force and self.session is not None and self.insurance_date:
                return True

            if self.session is not None:
                try:
                    self.session.close()
                except Exception:
                    pass
                self.session = None

            try:
                insurance_date, cookies = self._bootstrap_waf_cookies()
            except Exception as e:
                print(f"ERROR: לא ניתן לפתוח דפדפן לאימות האתר: {e}")
                return False

            last_error = None
            for impersonate in (True, False):
                try:
                    session = _create_http_session(impersonate=impersonate)
                except ImportError:
                    last_error = "curl_cffi missing"
                    continue
                self._apply_cookies(session, cookies)
                self.session = session
                self._session_kind = "curl_cffi" if impersonate else "requests"
                self.insurance_date = insurance_date or self._parse_insurance_date("")
                print(f"HTTP session מוכן ({self._session_kind}), תאריך ביטוח: {self.insurance_date}")
                return True

            print(f"ERROR: לא ניתן לפתוח חיבור HTTP לאתר הביטוח: {last_error}")
            return False

    def _parse_insurance_date(self, html):
        try:
            soup = BeautifulSoup(html, "lxml")
            field = soup.find(id="insurance_date")
            value = (field.get("value") or "").strip() if field else ""
            if value:
                return value
        except Exception:
            pass
        next_month = (datetime.now().replace(day=1) + timedelta(days=32)).replace(day=1)
        return next_month.strftime("%d/%m/%Y")

    def _post_calculate(self, payload, session=None):
        http = session or self.session
        calculate_url = getattr(config, "CMA_CALCULATE_URL", "https://car.cma.gov.il/Parameters/Calculate")
        response = http.post(
            calculate_url,
            data=payload,
            timeout=REQUEST_TIMEOUT,
            headers={
                **REQUEST_HEADERS,
                "Content-Type": "application/x-www-form-urlencoded",
                "Referer": config.MINISTRY_OF_TRANSPORT_URL,
            },
        )
        if _response_blocked(response):
            raise RuntimeError(f"האתר חסם את הבקשה (HTTP {response.status_code})")
        response.raise_for_status()
        return response.text

    def _switch_sheet(self, sheet_id, session=None):
        """ASP.NET שומר את סוג הרכב ב-session; חייבים להחליף לפני Calculate."""
        http = session or self.session
        sheet_url = getattr(
            config,
            "CMA_SHEET_PARAMS_URL",
            "https://car.cma.gov.il/Parameters/GetParametersPerSheet",
        )
        response = http.post(f"{sheet_url}?sheet_id={sheet_id}", timeout=REQUEST_TIMEOUT)
        if _response_blocked(response):
            raise RuntimeError(f"האתר חסם החלפת סוג רכב (HTTP {response.status_code})")
        response.raise_for_status()
        return True

    def _extract_harel_price_from_html(self, html):
        soup = BeautifulSoup(html, "lxml")
        table = soup.find(id="ResultTable") or soup.find("table")
        rows = table.find_all("tr") if table else soup.find_all("tr")
        for row in rows:
            cells = row.find_all("td")
            if not cells:
                continue
            texts = [cell.get_text(" ", strip=True) for cell in cells]
            if not any("הראל" in text for text in texts):
                continue
            for text in texts:
                if "הראל" in text:
                    continue
                price = self._parse_numeric_value(text)
                if price is not None and price >= PRICE_MIN:
                    return price
            prices = [
                self._parse_numeric_value(text)
                for text in texts
                if self._parse_numeric_value(text) is not None
                and self._parse_numeric_value(text) >= PRICE_MIN
            ]
            if prices:
                return max(prices)
        return None

    @staticmethod
    def _parse_numeric_value(raw_text):
        if not raw_text:
            return None
        cleaned = raw_text.replace("₪", "").replace(" ", "")
        match = re.search(r"\d[\d,]*(?:\.\d+)?", cleaned)
        if not match:
            return None
        try:
            return float(match.group(0).replace(",", ""))
        except ValueError:
            return None

    def _base_payload(self, sheet_id):
        return {
            "hdnForCaptcha": "",
            "sheet_id": str(sheet_id),
            "code_owner": "1001",
            "insurance_date": self.insurance_date,
        }

    def _private_payload(self, age, vol, lic):
        payload = self._base_payload(1)
        payload.update({
            "parameters[0].parameter": "D",
            "parameters[0].value": "1",
            "parameters[1].parameter": "D2",
            "parameters[1].value": str(age),
            "parameters[2].parameter": "E",
            "parameters[2].value": str(lic),
            "parameters[3].parameter": "F",
            "parameters[3].value": "0",
            "parameters[4].parameter": "G",
            "parameters[4].value": "0",
            "parameters[5].parameter": "N",
            "parameters[5].value": "1",
            "parameters[6].parameter": "A",
            "parameters[6].value": str(vol),
            "parameters[7].parameter": "O",
            "parameters[7].value": "100",
            "parameters[8].parameter": "J",
            "parameters[8].value": "1",
            "parameters[9].parameter": "K",
            "parameters[9].value": "1",
            "parameters[10].parameter": "H",
            "parameters[10].value": "4",
            "parameters[11].parameter": "L",
            "parameters[11].value": "2",
            "parameters[12].parameter": "M",
            "parameters[12].value": "2",
            "parameters[13].parameter": "B",
            "parameters[13].value": "6",
        })
        return payload

    def _commercial_payload(self, age, weight, lic):
        payload = self._base_payload(5)
        payload.update({
            "parameters[0].parameter": "D",
            "parameters[0].value": "1",
            "parameters[1].parameter": "D2",
            "parameters[1].value": str(age),
            "parameters[2].parameter": "E",
            "parameters[2].value": str(lic),
            "parameters[3].parameter": "F",
            "parameters[3].value": "0",
            "parameters[4].parameter": "G",
            "parameters[4].value": "0",
            "parameters[5].parameter": "A",
            "parameters[5].value": str(weight),
            "parameters[6].parameter": "N",
            "parameters[6].value": "1",
            "parameters[7].parameter": "B",
            "parameters[7].value": "9",
            "parameters[8].parameter": "J",
            "parameters[8].value": "1",
            "parameters[9].parameter": "K",
            "parameters[9].value": "1",
            "parameters[10].parameter": "L",
            "parameters[10].value": "2",
            "parameters[11].parameter": "M",
            "parameters[11].value": "2",
            "parameters[12].parameter": "H",
            "parameters[12].value": "2",
        })
        return payload

    def _special_payload(self, vehicle_code, age=19, lic=2):
        payload = self._base_payload(7)
        payload.update({
            "parameters[0].parameter": "D",
            "parameters[0].value": "1",
            "parameters[1].parameter": "D2",
            "parameters[1].value": str(age),
            "parameters[2].parameter": "E",
            "parameters[2].value": str(lic),
            "parameters[3].parameter": "F",
            "parameters[3].value": "0",
            "parameters[4].parameter": "G",
            "parameters[4].value": "0",
            "parameters[5].parameter": "A",
            "parameters[5].value": str(vehicle_code),
        })
        return payload

    def _quote_harel(self, payload, session=None, attempts=2):
        last_error = None
        http = session
        for attempt in range(1, attempts + 1):
            try:
                if http is None:
                    http = self._clone_session()
                html = self._post_calculate(payload, session=http)
                price = self._extract_harel_price_from_html(html)
                if price is not None:
                    return price
                last_error = "לא נמצא מחיר הראל"
            except Exception as e:
                last_error = e
                http = None
                if _is_waf_error(e):
                    print("WAF פג, מרענן cookies...")
                    if self._ensure_session(force=True):
                        sheet_id = payload.get("sheet_id")
                        if sheet_id:
                            try:
                                self._switch_sheet(sheet_id)
                            except Exception as switch_error:
                                print(f"WARNING: החלפת סוג רכב אחרי רענון נכשלה: {switch_error}")
                        http = self.session
                        continue
            if attempt < attempts:
                print(f"ניסיון {attempt}/{attempts} נכשל ({last_error}), מנסה שוב...")
        print(f"ERROR: לא נמצא מחיר הראל: {last_error}")
        return None

    def _all_jobs(self):
        jobs = []
        for age, vol, lic in PRIVATE_SCENARIOS:
            jobs.append({
                "kind": "private",
                "label": f"פרטי גיל {age} נפח {vol}",
                "payload": self._private_payload(age, vol, lic),
                "group": self._private_age_group(age),
                "col": self._private_col(vol),
            })
        for age, weight, lic in COMMERCIAL_SCENARIOS:
            jobs.append({
                "kind": "commercial",
                "label": f"מסחרי גיל {age} משקל {weight}",
                "payload": self._commercial_payload(age, weight, lic),
                "group": self._commercial_group(age),
                "col": "עד 4000 (כולל)" if weight == 4 else "מעל 4000",
            })
        for key, code in SPECIAL_SCENARIOS:
            jobs.append({
                "kind": "special",
                "label": f"מיוחד {key}",
                "payload": self._special_payload(code),
                "key": key,
            })
        return jobs

    def _empty_insurance_data(self):
        return {"private_car": {}, "commercial_car": {}, "special_vehicle": {}}

    def _store_job_price(self, insurance_data, job, price):
        if job["kind"] == "private":
            insurance_data["private_car"].setdefault(job["group"], {})[job["col"]] = price
        elif job["kind"] == "commercial":
            insurance_data["commercial_car"].setdefault(job["group"], {})[job["col"]] = price
        else:
            insurance_data["special_vehicle"][job["key"]] = price

    def _job_has_price(self, insurance_data, job):
        if job["kind"] == "private":
            return bool(insurance_data["private_car"].get(job["group"], {}).get(job["col"]))
        if job["kind"] == "commercial":
            return bool(insurance_data["commercial_car"].get(job["group"], {}).get(job["col"]))
        return bool(insurance_data["special_vehicle"].get(job["key"]))

    def _run_jobs(self, jobs, display_callback=None):
        insurance_data = self._empty_insurance_data()
        if not jobs:
            return insurance_data

        sheet_ids = {"private": 1, "commercial": 5, "special": 7}
        for kind in ("private", "commercial", "special"):
            kind_jobs = [job for job in jobs if job["kind"] == kind]
            if not kind_jobs:
                continue
            self._switch_sheet(sheet_ids[kind])
            if display_callback:
                display_callback(f"שולף {kind}: {len(kind_jobs)} תרחישים")
            for completed, job in enumerate(kind_jobs, 1):
                price = self._quote_harel(job["payload"], session=self.session)
                self._store_job_price(insurance_data, job, price)
                if price is not None:
                    print(f"OK {job['label']}: {price}")
                else:
                    print(f"FAIL {job['label']}")
                if display_callback:
                    status = f"{price} ₪" if price is not None else "נכשל"
                    display_callback(f"{completed}/{len(kind_jobs)} {job['label']}: {status}")
        return insurance_data

    def _merge_insurance_data(self, target, incoming):
        for group, cols in (incoming.get("private_car") or {}).items():
            target["private_car"].setdefault(group, {})
            for col, price in (cols or {}).items():
                if price is not None:
                    target["private_car"][group][col] = price
        for group, cols in (incoming.get("commercial_car") or {}).items():
            target["commercial_car"].setdefault(group, {})
            for col, price in (cols or {}).items():
                if price is not None:
                    target["commercial_car"][group][col] = price
        for key, price in (incoming.get("special_vehicle") or {}).items():
            if price is not None:
                target["special_vehicle"][key] = price
        return target

    def _retry_missing_insurance_scenarios(self, insurance_data, display_callback=None, max_rounds=2):
        jobs = self._all_jobs()
        for round_num in range(1, max_rounds + 1):
            missing = [job for job in jobs if not self._job_has_price(insurance_data, job)]
            if not missing:
                break
            msg = f"ניסיון חוזר {round_num}/{max_rounds} - חסרים {len(missing)} מחירים..."
            print(msg)
            if display_callback:
                display_callback(msg)
            retry_data = self._run_jobs(missing, display_callback=display_callback)
            self._merge_insurance_data(insurance_data, retry_data)
        return insurance_data

    def scrape_all_age_groups_complete(self):
        return self._scrape_private()

    def scrape_commercial_vehicle_complete(self):
        return self._scrape_commercial()

    def scrape_special_vehicle_data(self):
        return self._scrape_special()

    def scrape_all_insurance_data(self, update_callback=None, display_callback=None):
        """
        פונקציה מקיפה שמבצעת את כל תהליך השליפה והשמירה
        דומה ל-scrape_fuel_prices ב-fuel_scraper
        """
        results = {
            'private_success': 0,
            'commercial_success': 0,
            'special_success': 0,
            'total_success': 0,
            'image_path': None,
            'mdb_path': None,
            'par_rech_updated': False,
        }
        
        try:
            if update_callback:
                update_callback("מתחיל שליפה מלאה...")
            
            if display_callback:
                display_callback("שליפה מלאה - כל התרחישים דרך API")
                display_callback("רכב פרטי: 24 תרחישים")
                display_callback("רכב מסחרי: 10 תרחישים")
                display_callback("רכב מיוחד: 3 תרחישים")
                display_callback("סך הכל: 37 תרחישים")
                display_callback("פותח דפדפן לאימות קצר, ואז שולח בקשות HTTP...\n")

            if not self._ensure_session():
                if display_callback:
                    display_callback("שגיאה בחיבור לאתר הביטוח")
                results['error'] = "לא ניתן להתחבר לאתר הביטוח"
                return results

            if display_callback:
                display_callback("חיבור לאתר מוכן, שולח בקשות...")
            if update_callback:
                update_callback("שולף 37 תרחישים...")

            insurance_data = self._run_jobs(self._all_jobs(), display_callback=display_callback)

            mdb = _import_mdb_module()
            count_scraped_insurance_prices = mdb.count_scraped_insurance_prices
            has_sufficient_insurance_data = mdb.has_sufficient_insurance_data

            # ניסיון חוזר לתרחישים שנכשלו (למשל נגרר)
            insurance_data = self._retry_missing_insurance_scenarios(
                insurance_data,
                display_callback=display_callback,
                max_rounds=2,
            )

            private_results = insurance_data.get('private_car') or {}
            commercial_results = insurance_data.get('commercial_car') or {}
            special_results = insurance_data.get('special_vehicle') or {}
            results['private_success'] = sum(
                sum(1 for p in group.values() if p is not None)
                for group in private_results.values() if group
            )
            results['commercial_success'] = sum(
                sum(1 for p in group.values() if p is not None)
                for group in commercial_results.values() if group
            )
            results['special_success'] = sum(1 for p in special_results.values() if p is not None)
            results['total_success'] = (
                results['private_success'] + results['commercial_success'] + results['special_success']
            )
            if display_callback:
                display_callback(
                    f"\nאחרי ניסיונות חוזרים: {results['total_success']}/37 "
                    f"(פרטי {results['private_success']}/24, "
                    f"מסחרי {results['commercial_success']}/10, "
                    f"מיוחד {results['special_success']}/3)"
                )

            scraped_count = count_scraped_insurance_prices(insurance_data)
            if display_callback:
                display_callback(f"נשלפו {scraped_count}/37 מחירים")

            if not has_sufficient_insurance_data(insurance_data):
                msg = f"לא נשלפו נתונים כלל ({scraped_count}/37) - לא יוצרים קבצים"
                print(f"WARNING: {msg}")
                if display_callback:
                    display_callback(f"WARNING: {msg}")
                if update_callback:
                    update_callback(f"אין נתונים: {scraped_count}/37")
                results['insufficient_data'] = True
                results['scraped_count'] = scraped_count
                return results

            if scraped_count < 37:
                msg = f"נתונים חלקיים ({scraped_count}/37) - יוצרים KNE ו-par_rech בכל זאת"
                print(f"WARNING: {msg}")
                if display_callback:
                    display_callback(f"WARNING: {msg}")
                results['partial_data'] = True
                results['scraped_count'] = scraped_count
            
            # שמירת תמונה
            if display_callback:
                display_callback("📊 יוצר טבלאות...")
            print("STEP: save_tables_as_image...")
            results['image_path'] = self.save_tables_as_image(insurance_data)
            print(f"STEP: save_tables_as_image done -> {results['image_path']}")
            if results['image_path'] and display_callback:
                display_callback(f"📷 טבלאות נשמרו: {results['image_path']}")
            
            # שמירת MDB
            if display_callback:
                display_callback("\n📊 יוצר קובץ MDB...")
            if update_callback:
                update_callback("יוצר קובץ MDB...")
            
            print("STEP: create_mdb_database...")
            results['mdb_path'] = self.create_mdb_database(insurance_data)
            print(f"STEP: create_mdb_database done -> {results['mdb_path']}")
            if results['mdb_path'] and display_callback:
                display_callback(f"✅ קובץ MDB נוצר: {results['mdb_path']}")
                display_callback("📋 הקובץ כולל 3 טבלאות:")
                display_callback("• tblBituachHova_edit (1 שורה)")
                display_callback("• tblBituachHovaMishari_edit (5 שורות)")
                display_callback("• tblBituachHovaPrati_edit (6 שורות)")
            elif display_callback:
                display_callback("⚠️ יצירת MDB נכשלה")
            
            # עדכון קובץ par_rech.dat
            if display_callback:
                display_callback("\n📋 מעדכן קובץ par_rech.dat...")
            if update_callback:
                update_callback("מעדכן par_rech.dat...")
            
            print("STEP: update_par_rech_file...")
            results['par_rech_updated'] = self.update_par_rech_file(insurance_data)
            print(f"STEP: update_par_rech_file done -> {results['par_rech_updated']}")
            if results['par_rech_updated'] and display_callback:
                display_callback("קובץ par_rech.dat עודכן בהצלחה")
            elif display_callback:
                display_callback("WARNING: עדכון par_rech.dat נכשל - בדקי את הלוג")
            
            if update_callback:
                suffix = " + MDB + par_rech.dat" if results['par_rech_updated'] else " + MDB"
                update_callback(f"הושלם: {results['total_success']}/37{suffix}")
            
        except Exception as e:
            print(f"שגיאה בשליפה מקיפה: {e}")
            import traceback
            traceback.print_exc()
            results['error'] = str(e)
            if display_callback:
                display_callback(f"❌ שגיאה: {str(e)}")
        
        return results

    def _scrape_kind(self, kind):
        if not self._ensure_session():
            return {}
        jobs = [job for job in self._all_jobs() if job["kind"] == kind]
        data = self._run_jobs(jobs)
        if kind == "private":
            return data.get("private_car") or {}
        if kind == "commercial":
            return data.get("commercial_car") or {}
        return data.get("special_vehicle") or {}

    def _scrape_private(self):
        return self._scrape_kind("private")

    def _scrape_commercial(self):
        return self._scrape_kind("commercial")

    def _scrape_special(self):
        return self._scrape_kind("special")

    def _private_col(self, vol):
        if vol <= 1050:
            return "עד 1050"
        if vol <= 1550:
            return "מ-1051 עד 1550"
        if vol <= 2050:
            return "מ-1551 עד 2050"
        return "מ-2051 ומעלה"

    def _private_age_group(self, age):
        if age <= 20:
            return "17-20"
        if age <= 23:
            return "21-23"
        if age <= 29:
            return "24-29"
        if age <= 39:
            return "30-39"
        if age <= 49:
            return "40-49"
        return "50- ומעלה"

    def _commercial_group(self, age):
        if age <= 20:
            return "17-20"
        if age <= 23:
            return "21-23"
        if age <= 39:
            return "24-39"
        if age <= 49:
            return "40-49"
        return "50- ומעלה"

    # outputs
    def save_tables_as_image(self, insurance_data=None, save_path=None):
        try:
            import matplotlib
            matplotlib.use('Agg')
            import matplotlib.pyplot as plt

            mdb = _import_mdb_module()
            prepare_all_tables_data = mdb.prepare_all_tables_data
            get_bituah_effective_dates = mdb.get_bituah_effective_dates
            
            # אם לא סופק נתיב, נשתמש בנתיב מקובץ הקונפיג
            if save_path is None:
                save_path = config.BITUAH_RECHEV_OUTPUT_PATH
            
            # יצירת התיקיות אם לא קיימות
            try:
                os.makedirs(save_path, exist_ok=True)
                print(f"תיקייה מוכנה: {save_path}")
            except Exception as e:
                print(f"שגיאה ביצירת תיקייה: {e}")
                return None
            
            # תאריך עתידי - לשימוש בתוך הטבלה ולשם הקובץ (החודש הבא, כמו par_rech)
            next_month, effective_date_str, target_month_code = get_bituah_effective_dates()
            
            # שם קובץ לפי החודש הבא
            image_path = os.path.join(save_path, f"{target_month_code}.jpg")
            
            # מחיקת קובץ קיים אם קיים
            if os.path.exists(image_path):
                os.remove(image_path)
                print(f"🗑️ מחק קובץ תמונה קיים: {image_path}")
            
            print(f"📁 שם קובץ תמונה: {target_month_code}.jpg (חודש הבא)")
            print(f"📅 תאריך בטבלה: {effective_date_str} (חודש עתידי)")

            tables = prepare_all_tables_data(effective_date_str, insurance_data or {})
            
            # בדיקה שיש נתונים לפחות בטבלה אחת
            has_data = any(len(data['rows']) > 0 for data in tables.values())
            if not has_data:
                print("⚠️ אין נתונים ליצירת תמונה - יוצר תמונה עם הודעת 'אין נתונים'")
            
            fig, axes = plt.subplots(1, 3, figsize=(20, 8))
            for ax, name in zip(axes, ['tblBituachHovaPrati_edit','tblBituachHovaMishari_edit','tblBituachHova_edit']):
                data = tables[name]
                if len(data['rows']) > 0:
                    table = ax.table(cellText=data['rows'], colLabels=data['headers'], cellLoc='center', loc='center')
                    table.auto_set_font_size(False); table.set_fontsize(9); table.scale(1, 2)
                else:
                    # אם אין נתונים, נציג הודעה
                    ax.text(0.5, 0.5, 'אין נתונים', ha='center', va='center', fontsize=14)
                ax.set_xlim(ax.get_xlim()[::-1]); ax.axis('off')
            plt.tight_layout(); plt.savefig(image_path, dpi=300, bbox_inches='tight', format='jpg'); plt.close()
            print(f"✅ תמונה נשמרה: {image_path}")
            return image_path
        except Exception as e:
            print(f"❌ שגיאה ביצירת תמונה: {e}")
            import traceback
            traceback.print_exc()
            return None

    def create_mdb_database(self, insurance_data=None, save_path=None):
        try:
            mdb = _import_mdb_module()
            create_insurance_files = mdb.create_insurance_files
            
            # אם לא סופק נתיב, נשתמש בנתיב מקובץ הקונפיג
            if save_path is None:
                save_path = config.BITUAH_RECHEV_OUTPUT_PATH
            
            return create_insurance_files(save_path, insurance_data)
        except Exception as e:
            print(f"❌ שגיאה ביצירת MDB: {e}")
            import traceback
            traceback.print_exc()
            return None
    
    def update_par_rech_file(self, insurance_data):
        """עדכון קובץ par_rech.dat עם נתוני ביטוח חדשים. מחזיר True בהצלחה."""
        try:
            print("\n" + "=" * 60)
            print("מתחיל עדכון par_rech.dat")
            print("=" * 60)

            mdb = _import_mdb_module()
            if mdb.count_scraped_insurance_prices(insurance_data) < 1:
                print("WARNING: אין נתונים לעדכון par_rech.dat")
                return False

            # נתיב קריאה - מהשרת, עם fallback לקובץ מקומי (העדכני ביותר)
            par_rech_source_path = config.BITUAH_RECHEV_PARAM_SOURCE_FILE
            local_par_rech = os.path.join(config.BITUAH_RECHEV_OUTPUT_PATH, "par_rech.dat")
            print(f"נתיב מקור (קריאה): {par_rech_source_path}")

            def _last_00012_date(path):
                if not os.path.exists(path):
                    return None
                with open(path, 'r', encoding='cp862') as f:
                    lines = f.readlines()
                for line in reversed(lines):
                    if line.startswith('00012:'):
                        return line.split(':')[1].strip()
                return None

            server_date = _last_00012_date(par_rech_source_path)
            local_date = _last_00012_date(local_par_rech)
            if local_date and (not server_date or local_date > server_date):
                par_rech_source_path = local_par_rech
                print(f"משתמש בקובץ מקומי (עדכני יותר: {local_date}): {par_rech_source_path}")
            elif os.path.exists(par_rech_source_path):
                print(f"משתמש בקובץ מהשרת (תאריך אחרון: {server_date})")
            
            # נתיב כתיבה - לתיקייה המקומית
            par_rech_output_path = local_par_rech
            print(f"נתיב יעד (כתיבה): {par_rech_output_path}")
            
            if not os.path.exists(par_rech_source_path):
                print(f"WARNING: קובץ מקור לא נמצא בשרת: {config.BITUAH_RECHEV_PARAM_SOURCE_FILE}")
                if os.path.exists(local_par_rech):
                    par_rech_source_path = local_par_rech
                    print(f"משתמש בקובץ מקומי כמקור: {par_rech_source_path}")
                else:
                    print("ERROR: לא נמצא par_rech.dat לא בשרת ולא מקומית")
                    return False
            
            print("קובץ par_rech.dat נמצא במקור")
            
            # קריאת הקובץ מהמקור
            print("📖 קורא את הקובץ מהשרת...")
            with open(par_rech_source_path, 'r', encoding='cp862') as f:
                lines = f.readlines()
            
            if not lines:
                print("ERROR: קובץ par_rech.dat ריק")
                return False
            
            print(f"נמצאו {len(lines)} שורות בקובץ")
            
            # מציאת השורה האחרונה שמתחילה ב-00012:
            last_00012_line = None
            last_00012_index = -1
            for i, line in enumerate(lines):
                if line.startswith('00012:'):
                    last_00012_line = line.rstrip('\n\r')
                    last_00012_index = i
            
            if not last_00012_line:
                print("ERROR: לא נמצאה שורה שמתחילה ב-00012:")
                return False
            
            print(f"נמצאה שורה אחרונה ב-00012 (שורה {last_00012_index + 1})")
            print(f"📄 שורה: {last_00012_line[:80]}...")
            
            # קביעת תאריך חדש (חודש הבא) - אותה לוגיקה כמו KNE/MDB
            next_month, _, _ = mdb.get_bituah_effective_dates()
            new_date = f"{next_month.strftime('%y/%m')}"
            print(f"תאריך חדש: {new_date}")

            # פיצול השורה לפי :
            parts = last_00012_line.split(':')

            if len(parts) < 45:
                print(f"ERROR: מבנה שורה לא תקין, יש רק {len(parts)} חלקים")
                return False

            replace_existing = parts[1].strip() == new_date
            if replace_existing:
                print(f"WARNING: שורת 00012 לחודש {new_date} כבר קיימת - מעדכן במקום")
            
            # פונקציה עזר לשמירת פורמט הרווחים
            def format_value_preserve_spaces(original_part, new_value):
                """שומר על הרווחים של החלק המקורי ומחליף רק את הערך"""
                # ספירת רווחים בהתחלה ובסוף
                leading_spaces = len(original_part) - len(original_part.lstrip())
                trailing_spaces = len(original_part) - len(original_part.rstrip())
                # בניית הערך החדש עם אותם רווחים
                return ' ' * leading_spaces + str(new_value) + ' ' * trailing_spaces
            
            # עדכון התאריך - שומר על הפורמט
            parts[1] = format_value_preserve_spaces(parts[1], new_date)
            
            # עדכון נתוני רכב פרטי (6 קבוצות גיל, 4 נפחי מנוע לכל אחת)
            private_data = insurance_data.get('private_car', {})
            age_groups_order = ['17-20', '21-23', '24-29', '30-39', '40-49', '50- ומעלה']
            engine_sizes_order = ['עד 1050', 'מ-1051 עד 1550', 'מ-1551 עד 2050', 'מ-2051 ומעלה']
            
            part_index = 2  # מתחיל אחרי התאריך
            print("\n💰 מעדכן נתוני רכב פרטי:")
            for age_group in age_groups_order:
                age_value = age_group.split('-')[0]  # 17, 21, 24, 30, 40, 50
                parts[part_index] = format_value_preserve_spaces(parts[part_index], age_value)
                part_index += 1
                
                print(f"   🚗 קבוצת גיל {age_group}:")
                for engine_size in engine_sizes_order:
                    price = private_data.get(age_group, {}).get(engine_size)
                    if price:
                        parts[part_index] = format_value_preserve_spaces(parts[part_index], int(price))
                        print(f"      • {engine_size}: {int(price)}")
                    part_index += 1
            
            # עדכון נתוני רכב מסחרי (5 קבוצות גיל, 2 משקלים לכל אחת)
            commercial_data = insurance_data.get('commercial_car', {})
            commercial_age_groups_order = ['17-20', '21-23', '24-39', '40-49', '50- ומעלה']
            weight_categories_order = ['עד 4000 (כולל)', 'מעל 4000']
            
            print("\n🚛 מעדכן נתוני רכב מסחרי:")
            for age_group in commercial_age_groups_order:
                age_value = age_group.split('-')[0]  # 17, 21, 24, 40, 50
                parts[part_index] = format_value_preserve_spaces(parts[part_index], age_value)
                part_index += 1
                
                print(f"   🚚 קבוצת גיל {age_group}:")
                for weight in weight_categories_order:
                    price = commercial_data.get(age_group, {}).get(weight)
                    if price:
                        parts[part_index] = format_value_preserve_spaces(parts[part_index], int(price))
                        print(f"      • {weight}: {int(price)}")
                    part_index += 1
            
            # עדכון נתוני רכב מיוחד (3 סוגים)
            special_data = insurance_data.get('special_vehicle', {})
            special_types_order = ['Nigrar', 'Handasi', 'Agricalture']
            
            print("\n🚜 מעדכן נתוני רכב מיוחד:")
            for special_type in special_types_order:
                price = special_data.get(special_type)
                if price:
                    parts[part_index] = format_value_preserve_spaces(parts[part_index], int(price))
                    print(f"   • {special_type}: {int(price)}")
                part_index += 1
            
            # בניית השורה החדשה
            new_line = ':'.join(parts)
            
            print(f"\nשורה מעודכנת:")
            print(f"   {new_line[:100]}...")
            
            print("\nכותב קובץ מעודכן לתיקייה המקומית...")
            if replace_existing:
                lines[last_00012_index] = new_line + '\n'
                print(f"   מחליף שורה קיימת במיקום {last_00012_index + 1}")
            else:
                if last_00012_index >= 0 and last_00012_index < len(lines):
                    if not lines[last_00012_index].endswith('\n'):
                        lines[last_00012_index] = lines[last_00012_index] + '\n'
                lines.insert(last_00012_index + 1, new_line + '\n')
                print(f"   מוסיף שורה חדשה במיקום {last_00012_index + 2}")
                print(f"   סה\"כ שורות בקובץ החדש: {len(lines)}")
            
            # כתיבת הקובץ המעודכן לתיקייה היעד
            with open(par_rech_output_path, 'w', encoding='cp862') as f:
                f.writelines(lines)
            
            print(f"קובץ par_rech.dat עודכן בהצלחה")
            print(f"נקרא מ: {par_rech_source_path}")
            print(f"נשמר ב: {par_rech_output_path}")
            print("=" * 60 + "\n")
            return True
            
        except Exception as e:
            print(f"ERROR: שגיאה בעדכון par_rech.dat: {str(e)}")
            import traceback
            traceback.print_exc()
            print("=" * 60 + "\n")
            return False
